# Generated by Django 4.2.11 on 2024-05-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_suggestionnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
